### ISSUE TITLE
Demo takes 30s to show up

### ISSUE THREAD

**Issue by blueridanus** [msiglreith/gfx_ocean#2]
On my machine, there's a long delay(31.7s) between window creation and the demo displaying.

**Comment by blueridanus** [comment]
If speedup is not possible, perhaps it would be useful to output some progress messages to the console as the program loads, so it's clear it's not frozen.

**Comment by msiglreith** [comment]
Removed runtime generation of ocean spectrum and load it from file instead. Should be faster now.
