### ISSUE TITLE
"fix-cargo" branch appears to be missing

### ISSUE THREAD

**Issue by coder543** [msiglreith/gfx_ocean#3]
the "fix-cargo" branch appears to be missing on your fork of `gfx`, so this no longer compiles.

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/msiglreith/gfx.git`
error: failed to load source for a dependency on `gfx-backend-vulkan`

Caused by:
  Unable to update https://github.com/msiglreith/gfx.git?branch=fix-cargo
```

**Comment by msiglreith** [comment]
Thanks, looking into it! I haven't updated it in awhile :D

**Comment by msiglreith** [comment]
Build should be working now and Vulkan backend runs.
DX12 crashes atm, need to investigate!

**Comment by msiglreith** [comment]
Small typo in the dx12 backend, I will update the gfx-rs revision once the patch has landed.
(https://github.com/gfx-rs/gfx/pull/1713)

Everything should be up and running then 🌊

**Comment by msiglreith** [comment]
Should be fixed now
